### ISSUE TITLE
Override particlesStyle?

### ISSUE THREAD

**Issue by oscar-b** [kr1tzy/ReactParticles.js#5]
Nice component :)

It would be nice if there was no `style`, so you can place the particles anywhere. Or that you can override with your own style?

**Comment by kr1tzy** [comment]
You can customize it as far as the original particles.js and configure each component independently. Is there further customization you’d like to see other than that?

**Comment by oscar-b** [comment]
Yes overriding the CSS style which now puts the container at 100% width and so on, or am I reading the source wrong?

**Comment by oscar-b** [comment]
I'm talking about this part:

https://github.com/kr1tzb1tz/reactparticles.js/blob/master/src/Particles.js#L5-L12

**Comment by kr1tzy** [comment]
Done with the recent update
